/*
 * This source file was generated by the Gradle 'init' task
 */
package threads;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testThreadRunner() {
        ThreadRunner.runThreads(3, 6);
        assertTrue(true);
    }  

     @Test void testThreadRunnableLambda() {
        ThreadRunnableLambda.runThreads(7);
        assertTrue(true);
     }


     @Test void testThreadExecutorService() {
        ThreadExecutorService.runThreads(7);
        assertTrue(true);
     }

    @Test void testThreadCompletableFutureSupplySync() throws Exception{
        ThreadCompletableFuture.runSupplySyncThreads(5);
    }

    @Test void testThreadCompletableFutureASync() throws Exception {
        ThreadCompletableFuture.runAsyncThreads(5);
     }
}
